{{- if and (or (.Files.Glob "files/pgpool-entrypoint-initdb.d/*.sh") .Values.pgpool.initdbScripts) (not .Values.pgpool.initdbScriptsCM) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-initdb-scripts" (include "postgresql-ha.pgpool" .) }}
  labels: {{- include "postgresql-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
    {{- if .Values.commonLabels }}
    {{- include "postgresql-ha.tplValue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "postgresql-ha.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- with .Files.Glob "files/pgpool-entrypoint-initdb.d/*.sh" }}
  {{- .AsConfig | nindent 2 }}
  {{- end }}
  {{- with .Values.pgpool.initdbScripts }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
