{{- if (include "postgresql-ha.pgpoolCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-ha.pgpool" . }}
  labels: {{- include "postgresql-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgpool
    {{- if .Values.commonLabels }}
    {{- include "postgresql-ha.tplValue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "postgresql-ha.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password: {{ (include "postgresql-ha.pgpoolAdminPassword" .) | b64enc | quote }}
{{- end -}}
